# Generated by Django 4.1 on 2023-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usedcarinfo", "0002_alter_auto_part_options_auto_part_unique_auto_part"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="date",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="maintenance_schedule",
            options={
                "ordering": ["year__year", "period__period_sequence", "date__date"]
            },
        ),
        migrations.AlterModelOptions(
            name="period",
            options={"ordering": ["period_sequence"]},
        ),
        migrations.AlterModelOptions(
            name="year",
            options={"ordering": ["year"]},
        ),
        migrations.RemoveField(
            model_name="maintenance_schedule",
            name="month",
        ),
        migrations.AddConstraint(
            model_name="maintenance_schedule",
            constraint=models.UniqueConstraint(
                fields=("year", "period", "date"), name="unique_maintenance_schedule"
            ),
        ),
        migrations.DeleteModel(
            name="Month",
        ),
    ]
